import turtle

# Configurar la pantalla
screen = turtle.Screen()
screen.title("Laberinto con Turtle")
#screen.bgcolor("black")#color fondo
#screen.setup(1000, 700)
#screen.bgpic("fondo.jpg")
screen.bgpic("laberinto.gif")

# Crear instancia de Turtle
tortuga = turtle.Turtle()
tortuga.shape('turtle')
tortuga.color('black')#color 
#tortuga.width(2)#ancho linea
tortuga.penup()
tortuga.goto(-260, -285)
tortuga.pendown()
tortuga.speed(8)# Velocidad máxima


for i in range (1,8):
    if i == 1:
        tortuga.forward(85)
        tortuga.left(90)
        tortuga.forward(102)
        tortuga.right(90)
        tortuga.forward(120)
        tortuga.right(90)
    elif i == 2:
        tortuga.color('red')
        tortuga.forward(50)
        tortuga.left(90)
        tortuga.forward(200)
        tortuga.right(90)
        tortuga.forward(50)
        tortuga.left(90)
        tortuga.forward(80)
        tortuga.left(90)
        tortuga.forward(50)
        tortuga.left(90)
        tortuga.forward(30)

        tortuga.left(180)
        tortuga.forward(30)
        tortuga.right(90)
        tortuga.forward(50)
        tortuga.right(90)
        tortuga.forward(80)
        tortuga.right(90)
        tortuga.forward(50)
        tortuga.left(90)
        tortuga.forward(200)
        tortuga.right(90)
        tortuga.forward(50)
    elif i == 3:
        tortuga.color('black')
        tortuga.forward(50)
        tortuga.left(90)
        tortuga.forward(120)
        tortuga.right(90)
        tortuga.forward(60)
        tortuga.right(90)
        tortuga.forward(165)
        tortuga.left(90)
        tortuga.forward(55)
        tortuga.left(90)
        tortuga.forward(55)
    elif i == 4:
        tortuga.color('red')
        tortuga.forward(160)
        tortuga.left(90)
        tortuga.forward(220)
        #vuelta
        #vuelta
        tortuga.left(180)
        tortuga.forward(220)
        tortuga.right(90)
        tortuga.forward(160)
    elif i == 5:
        tortuga.left(90)
        tortuga.color('black')
        tortuga.forward(70)
        tortuga.right(90)
        tortuga.forward(85)
        tortuga.left(90)
        tortuga.forward(50)
        tortuga.right(90)
        tortuga.forward(40)
        tortuga.left(90)
    elif i == 6:
        tortuga.color('red')
        tortuga.forward(125)
        tortuga.right(90)
        tortuga.forward(55)
        tortuga.right(90)
        tortuga.forward(70)
        tortuga.left(90)
        tortuga.forward(50)
        tortuga.left(90)
        tortuga.forward(25)
        #vuelta
        tortuga.left(180)
        tortuga.forward(25)
        tortuga.right(90)
        tortuga.forward(50)
        tortuga.right(90)
        tortuga.forward(70)
        tortuga.left(90)
        tortuga.forward(55)
        tortuga.left(90)
        tortuga.forward(125)
    else:
        tortuga.left(90)
        tortuga.color('black')
        tortuga.forward(170)
        tortuga.left(90)
        tortuga.forward(125)
        tortuga.left(90)
        tortuga.forward(55)
        tortuga.right(90)
        tortuga.forward(55)
        tortuga.right(90)
        tortuga.forward(55)
        tortuga.left(90)
        tortuga.forward(30)
        for i in range (360):
            #tortuga.forward(1/2)
            tortuga.right(7)

    print(i)
    
turtle.done()      

"""#1
tortuga.forward(85)
tortuga.left(90)
tortuga.forward(102)
tortuga.right(90)
tortuga.forward(120)
tortuga.right(90)
#2
tortuga.color('red')
tortuga.forward(50)
tortuga.left(90)
tortuga.forward(200)
tortuga.right(90)
tortuga.forward(50)
tortuga.left(90)
tortuga.forward(80)
tortuga.left(90)
tortuga.forward(50)
tortuga.left(90)
tortuga.forward(30)
#vuelta
tortuga.left(180)
tortuga.forward(30)
tortuga.right(90)
tortuga.forward(50)
tortuga.right(90)
tortuga.forward(80)
tortuga.right(90)
tortuga.forward(50)
tortuga.left(90)
tortuga.forward(200)
tortuga.right(90)
tortuga.forward(50)
#3
tortuga.color('black')
tortuga.forward(50)
tortuga.left(90)
tortuga.forward(120)
tortuga.right(90)
tortuga.forward(60)
tortuga.right(90)
tortuga.forward(165)
tortuga.left(90)
tortuga.forward(55)
tortuga.left(90)
tortuga.forward(55)

#4
tortuga.color('red')
tortuga.forward(160)
tortuga.left(90)
tortuga.forward(220)
#vuelta
tortuga.left(180)
tortuga.forward(220)
tortuga.right(90)
tortuga.forward(160)
#5
tortuga.left(90)
tortuga.color('black')
tortuga.forward(70)
tortuga.right(90)
tortuga.forward(85)
tortuga.left(90)
tortuga.forward(50)
tortuga.right(90)
tortuga.forward(40)
tortuga.left(90)
#6
tortuga.color('red')
tortuga.forward(125)
tortuga.right(90)
tortuga.forward(55)
tortuga.right(90)
tortuga.forward(70)
tortuga.left(90)
tortuga.forward(50)
tortuga.left(90)
tortuga.forward(25)
#vuelta
tortuga.left(180)
tortuga.forward(25)
tortuga.right(90)
tortuga.forward(50)
tortuga.right(90)
tortuga.forward(70)
tortuga.left(90)
tortuga.forward(55)
tortuga.left(90)
tortuga.forward(125)
#7
tortuga.left(90)
tortuga.color('black')
tortuga.forward(170)
tortuga.left(90)
tortuga.forward(125)
tortuga.left(90)
tortuga.forward(55)
tortuga.right(90)
tortuga.forward(55)
tortuga.right(90)
tortuga.forward(55)
tortuga.left(90)
tortuga.forward(30)

for i in range (360):
    #tortuga.forward(1/2)
    tortuga.right(7)"""

